#!/bin/ env bash
# Assigning a variable to the argument
ARGUMEN=$1

# passing the argument
echo "arg1: $ARGUMENT"

# The script below run the whoami command under the user passed as an argument
sudo -u "$1" whoami
